name: Notify Deploy Bot via Make
on:
  push:
    branches:
      - '**'
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Add deploy commit
        run: |
          git config user.email "alexis.petrement@infinit.com"
          git config user.name "apetrementinfinit"
          git commit --allow-empty -m "[skip ci] Trigger deploy to Vercel"
          git push
      
      - name: Send commit info to Make
        run: |
          curl -X POST "https://hook.eu1.make.com/xvyuaszs86fhwsinzd8szuvxqobcfari" \
            -H "Content-Type: application/json" \
            -d "{
              \"repo\": \"${{ github.repository }}\",
              \"branch\": \"${{ github.ref_name }}\",
              \"commit\": \"$(git rev-parse HEAD)\"
            }"
