name: Notify Deploy Bot via Make
on:
  push:
    branches:
      - '**'
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send commit info to Make
        run: |
          curl -X POST "https://hook.eu1.make.com/xvyuaszs86fhwsinzd8szuvxqobcfari" \
            -H "Content-Type: application/json" \
            -d "{
              \"repo\": \"${{ github.repository }}\",
              \"branch\": \"${{ github.ref_name }}\",
              \"commit\": \"${{ github.sha }}\"
            }"
